### ISSUE TITLE
fitbitr does not expose restingHeartRate

### ISSUE THREAD

**Issue by andremi** [mrkaye97/fitbitr#11]
Thank you for the awesome package, it makes interfacing with the fitbit very easy.

The fitbit API ( https://dev.fitbit.com/build/reference/web-api/heartrate-timeseries/get-heartrate-timeseries-by-date-range/ )
in addition to HeartRateZone also provides restingHeartRate as a part of the response data.

The get_heart_rate_zones -- which calls the fitbit API above -- does not return restingHeartRate in the dataframe (and also does not return customHeartRateZone which the API also provides).

Please incorporate restingHeartRate into the datastructure returned by get_heart_rate_zones() (which would save on the number of the API calls) or expose it through a different function.

Thanks

```r
1. execute the following 
start_date <- lubridate::today() - lubridate::weeks(1)
end_date <- lubridate::today()

get_heart_rate_zones(start_date, end_date)

2. observe no restingHeartRate  in the returned data 

```

**Comment by mrkaye97** [comment]
Hey, sorry for never getting around to this. I can take a look, but I'm not actively maintaining this package anymore. Feel free to submit a PR if you like!
