### ISSUE TITLE
The app you're trying to connect did not provide valid information to Fitbit. Please report this issue to them.

### ISSUE THREAD

**Issue by durraniu** [mrkaye97/fitbitr#3]
Hi,

Thank you for creating this package. I have followed the instructions in read me and created the app.

Now, I am doing the following:

```
library(fitbitr)

generate_token(
  client_id = "xxxxx",
  client_secret = "xxxxxxxxxxx",
    callback = "http://localhost:1410/"
)

```

But that shows this message: 
The app you're trying to connect did not provide valid information to Fitbit. Please report this issue to them.

Could you please guide me where I am making a mistake? Thank you.

**Comment by mrkaye97** [comment]
Tough for me to help you debug this without knowing exactly what you're running, but my sense is that "Please report this issue to them" indicates it might be something wrong in a) how you created the app or b) on their end.

With that said, I haven't touched this package in almost a year and am not actively maintaining it, so I can't guarantee that there hasn't been a breaking change in the API contract

**Comment by durraniu** [comment]
Thank you for your response. I created 2 apps. For some reason, `generate_token` works for one but not for the other. 

The working app also warns to use `https` while generating the token. But it is working. 

Thank you for your hard work. I can visualize my data now with help from your blog post.
