### ISSUE TITLE
token refresh only prompts to console

### ISSUE THREAD

**Issue by cstephens32** [mrkaye97/fitbitr#5]
I am trying to load a token on a shiny app, but once it times out token refresh does not work as the console must be reached. 

Can you make the default to TRUE for do_refresh or at least provide an option to change this to true?

function (reason, error_message) 
{
  inform(sprintf("%s. Error message: \n\n", reason))
  inform(error_message$message)
  inform("\n")
  do_refresh <- askYesNo("Would you like to generate a new token?", 
    default = FALSE, prompts = c("y", "n", "c"))
  if (do_refresh & !is.na(do_refresh)) {
    inform("Trying to generate a new token...")
    .fitbitr_token$init_credentials()
  }
  else {
    abort("No token was found, and a new one was not generated.")
  }
  invisible()
}

**Comment by mrkaye97** [comment]
Closing. See https://github.com/mrkaye97/fitbitr/pull/6#issuecomment-1480463925
